[project]
name = "py2048"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "textual>=7.2.0",
]

[project.scripts]
test = "test_runner:main"
auto = "auto_play:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = [
    "auto_play",
    "auto_players",
    "game2048",
    "main",
    "test_runner",
    "textual_animation",
    "textual_board",
]

[tool.setuptools.packages.find]
include = ["strategies"]
